import Head from "next/head";

import styles from "@/styles/Home.module.scss";

import { Space_Mono } from "next/font/google";
const space = Space_Mono({ subsets: ["latin"], weight: "700" });

import { Header, Main } from "@/components/_index";

export default function Home() {
    return (
        <div className={`${styles.home_container} ${space.className}	`}>
            <Head>
                <title>Frontend Mentor | Tip calculator app</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>
            <Header />
            <Main />
        </div>
    );
}
